name: Changesets

# NOTE: Don't use 'skip ui' + changeset. It cause stop CI.
# skip when doesn't have changesets
on:
  push:
    branches: ['main']
    paths:
      - '.changeset/**.md'

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

# skip when commit's scope name contains 'skip ci'
jobs:
  release:
    if: >-
      ${{
        github.repository == 'seeyouletter/seeyouletter-fe' &&
        !contains(github.event.head_commit.message, '(skip ci)') &&
        !contains(github.event.head_commit.message, 'changeset-release/main')
      }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: update versions"
          title: "chore: update versions"
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}